# This file generates the GitHub Actions matrix
include:
  # 1. Прошивка для левой половины KLOR Polydactyl (на Pro Micro nRF52840)
  - board: nice_nano_v2
    shield: klor_left

  # 2. Прошивка для правой половины KLOR Polydactyl (на Pro Micro nRF52840)
  - board: nice_nano_v2
    shield: klor_right

  # 3. КРИТИЧЕСКИ ВАЖНО: Прошивка для донгла с экраном YADS (на XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: klor_dongle

  # 4. Файл очистки памяти для nice_nano_v2 (пригодится, если половины не захотят связываться)
  - board: nice_nano_v2
    shield: settings_reset

  # 5. Файл очистки памяти для контроллера донгла XIAO BLE
  - board: seeeduino_xiao_ble
    shield: settings_reset
