# ==========================================================================
# ОСНОВНЫЕ НАСТРОЙКИ КЛАВИАТУРЫ KLOR
# ==========================================================================

# Включение поддержки энкодеров на половинках клавиатуры
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ОТКЛЮЧАЕМ старые OLED-экраны половинок для жесткой экономии заряда аккумулятора
CONFIG_ZMK_DISPLAY=n

# ПОДНЯТИЕ МОЩНОСТИ ПЕРЕДАТЧИКА ДО МАКСИМУМА (+8 dBm) ДЛЯ СТАБИЛЬНОЙ СВЯЗИ
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ==========================================================================
# ЭНЕРГОСБЕРЕЖЕНИЕ И РЕЖИМ СНА ПОЛОВИНОК (Для Pro Micro nRF52840)
# ==========================================================================
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ==========================================================================
# НАСТРОЙКИ ПОДСВЕТКИ КЛАВИШ (RGB Underglow)
# ==========================================================================
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Автоматически гасить подсветку при бездействии (через 30 секунд)
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Гасить подсветку, если половины питаются только от аккумулятора (кабель USB отключен)
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

# Стартовая яркость подсветки по умолчанию при включении (40%)
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=40

# Стартовый анимационный эффект (3 — мягкая волна)
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
