# ==========================================================================
# ОСНОВНЫЕ НАСТРОЙКИ КЛАВИАТУРЫ KLOR
# ==========================================================================

# Включение поддержки энкодеров на половинках клавиатуры
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ОТКЛЮЧАЕМ старые OLED-экраны половинок для жесткой экономии заряда аккумулятора
CONFIG_ZMK_DISPLAY=n

# ПОДНЯТИЕ МОЩНОСТИ ПЕРЕДАТЧИКА ДО МАКСИМУМА (+8 dBm) ДЛЯ СТАБИЛЬНОЙ СВЯЗИ
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ==========================================================================
# ЭНЕРГОСБЕРЕЖЕНИЕ И РЕЖИМ СНА ПОЛОВИНОК (Для Pro Micro nRF52840)
# ==========================================================================
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
