manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: janpfischer
      url-base: https://github.com
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    # Подключаем графический модуль экрана YADS в отдельную папку
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
      path: zmk-dongle-screen # <--- ИСПРАВЛЕНО (было "config")
  self:
    path: config
