# Переводим контроллер донгла в режим центрального узла
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# ВКЛЮЧАЕМ ZMK STUDIO (Изменение функций клавиш и крутилок "на лету" без перепрошивки)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Включаем поддержку энкодеров на стороне донгла, чтобы он принимал сигналы от половинок
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Настройки Bluetooth-профилей (выделяем по 5 слотов под сопряженные устройства)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Разрешаем донглу транслировать детальный статус на экран YADS
CONFIG_ZMK_STATUS_ADVERTISEMENT=y

# ПОДНЯТИЕ МОЩНОСТИ ПЕРЕДАТЧИКА ДО МАКСИМУМА (+8 dBm) ДЛЯ СТАБИЛЬНОСТИ ДОНГЛА
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Синхронизация RGB-эффектов подсветки половинок через центральный донгл
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
