# Включение поддержки энкодеров по умолчанию
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ОТКЛЮЧАЕМ старый OLED дисплей половин для совместимости с донглом YADS
CONFIG_ZMK_DISPLAY=n

# Включение RGB подсветки клавиш по умолчанию
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
