# ========== Подсветка WS2812 ==========
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# ========== Энкодер ==========
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ========== Дисплей половинки (OLED) ==========
# Раскомментируй, если на правой половинке есть OLED:
# CONFIG_ZMK_DISPLAY=y
