on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Переключаем сам сборщик GitHub Actions на стабильную ветку v0.3
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3-branch
